---
params:
  type: "cell"
  subtype: "cell"
  query: "HEPG2"
  content: "HEPG2"
  private: "true"
knitr:
  opts_chunk: 
    cache.lazy: false #fixes "Error in lazyLoadDBinsertVariable; long vectors not supported yet"
---

{{< include _setup.qmd >}}

#### Protein Expression Plot

```{r}
#| label: cell-protein-expression-setup
#| echo: false
#| message: false
#| warning: false

fig_legend <- make_legend(fun = "make_cellexpression")
```

```{r}
#| label: cell-protein-expression
#| echo: false
#| message: false
#| warning: false
#| eval: !expr private_report

make_cellexpression(input = input_report, var = "protein")
```

`r if(params$private == "true"){fig_legend} else {private_message_md}`

#### Protein Expression Table

```{r}
#| label: cell-protein-expression-table-setup
#| echo: false
#| message: false
#| warning: false

fig_legend <- make_legend(fun = "make_expression_table")
```

```{r}
#| label: cell-protein-expression-table
#| echo: false
#| message: false
#| warning: false
#| eval: !expr private_report

make_expression_table(input = input_report, var = "protein") %>% 
  gt::gt()
```

`r if(private_report == TRUE){fig_legend} else {private_message_md}`

