---
format: 
  html:
    self-contained: true
params:
  type: "gene"
  subtype: "gene"
  content: "ROCK1"
  private: "true"
title: "`r params$content` Report"
---

{{< include _setup.qmd >}}

### from `r dplyr::if_else(params$private == "true", paste0("datadrivenhypothesis.com"), paste0("datadrivenhypothesis.org"))`  
`r lubridate::stamp("Report generated December 31, 1979")(now())`  
  
## Project Summary  
{{< include _project-summary.qmd >}}  
{{< pagebreak >}}  
  
## Gene Summary  
{{< include _gene-summary.qmd >}}  
{{< pagebreak >}}  
  
### Ideogram
{{< include _gene-ideogram.qmd >}}  
{{< pagebreak >}}  
  
### GO Pathways
{{< include _gene-pathways.qmd >}}  
{{< pagebreak >}}  
  
## Protein Summary  
### Protein Size
{{< include _protein-size.qmd >}}  
{{< pagebreak >}}  
  
### Protein Sequence  
{{< include _protein-sequence.qmd >}}  
{{< pagebreak >}}  
  
### Protein Signature
{{< include _protein-signature.qmd >}}  
{{< pagebreak >}}  
  
### Protein Structure
{{< include _protein-structure.qmd >}}  
{{< pagebreak >}}  
  
## Literature {#sec-literature}
{{< include _literature.qmd >}}  
{{< pagebreak >}}  
  
## Expression  
### Subcellular Location
{{< include _gene-cellanatogram.qmd >}}  
{{< pagebreak >}}  
  
### Cell Line Expression
{{< include _gene-cellexpression.qmd >}}  
{{< pagebreak >}}  
  
### Tissue Distribution
{{< include _gene-tissuedistribution.qmd >}}  
{{< pagebreak >}}  
  
## Compounds
### Drugs
{{< include _gene-drugs.qmd >}}  
{{< pagebreak >}}  
  
### Metabolites
{{< include _gene-metabolites.qmd >}}  
{{< pagebreak >}}  
  
### Bipartite Graph
{{< include _gene-bipartite.qmd >}}  
{{< pagebreak >}}  

## Dependencies
### Dependency Plot
{{< include _gene-dependency.qmd >}}  
{{< pagebreak >}} 
  
### Depenedency Density Plot
{{< include _gene-dependency-density.qmd >}}  
{{< pagebreak >}} 
  
### Dependency Lineage Plot
{{< include _gene-dependency-lineage.qmd >}}  
{{< pagebreak >}} 
  
### Dependency Sublineage Plot
{{< include _gene-dependency-sublineage.qmd >}}  
{{< pagebreak >}} 
  
### Dependency Table
{{< include _gene-dependency-table.qmd >}}  
{{< pagebreak >}} 
  
### Gene expression v. gene dependency
{{< include _gene-dependency-v-expression.qmd >}}  
{{< pagebreak >}} 
  
### Co-essentiality Plot
{{< include _gene-coessentiality.qmd >}}  
{{< pagebreak >}} 
  
### Co-essentiality Table
{{< include _gene-coessentiality-table.qmd >}}  
{{< pagebreak >}} 
  
### Co-essentiality Positive Enrichment
{{< include _gene-coessentiality-positive.qmd >}}  
{{< pagebreak >}} 
  
### Co-essentiality Inverse Table
{{< include _gene-coessentiality-inverse-table.qmd >}}  
{{< pagebreak >}} 
  
### Co-essentiality Negative Enrichment
{{< include _gene-coessentiality-negative.qmd >}}  
{{< pagebreak >}} 
  
### Co-essentiality Graph
{{< include _gene-coessentiality-graph.qmd >}}  
{{< pagebreak >}} 
  
### Co-essential Drugs
{{< include _gene-coessentiality-drugs.qmd >}}  
{{< pagebreak >}} 
  
  