---
format: 
  html:
    self-contained: true
    toc: true
    toc-depth: 3
params:
  type: "gene"
  subtype: "gene"
  query: "ROCK1"
  content: "ROCK1"
  private: "true"
title: "`r params$content` Report"
knitr:
  opts_chunk: 
    cache.lazy: false #fixes "Error in lazyLoadDBinsertVariable; long vectors not supported yet"
---

```{r}
#| label: gene-tissuedistribution-setup
#| echo: false
#| message: false
#| warning: false
library(ddh)
library(patchwork)
load_ddh_data(app_data_dir = here::here("data"), #defined in setup
              object_name = c("female_tissue", "male_tissue"))

fig_legend_a <- make_legend(fun = "make_female_anatogram")
fig_legend_b <- make_legend(fun = "make_male_anatogram")

#CONVERT PARAMS TO LIST----
input_report = list(
  type = params$type, 
  subtype = params$subtype, 
  query = unlist(stringr::str_split(params$query, pattern = ", ")), 
  content = unlist(stringr::str_split(params$content, pattern = ", "))
)
```

```{r}
#| label: gene-tissuedistribution
#| echo: false
#| message: false
#| warning: false
#| fig-height: 7.5
#| fig-width: 12

a <- make_female_anatogram(input = input_report) #defined in setup
b <- make_male_anatogram(input = input_report) #defined in setup
  #make_tissue(input = list(type = params$type, content = params$content))

a+b
```
  
The tissue anatogram plot shows the distribution of `r params$content` across the human body. 
